name: CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version:
          - "18.17.0"
          - "18.18.0"
          - "20.7.0"
          - "20.8.0"
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - run: npm ci

      - run: node test.js
